### ISSUE TITLE
FreeBSD gnat-10.2.0-gnatcoll_sqlite.tar.xz links to a 403 page.

### ISSUE THREAD

**Issue by ALPHA-60** [annexi-strayline/gnat-packs#1]
The https://gnat-packs.annexi-strayline.com/x86_64-fsf-freebsd12.2/gnat-10.2.0-gnatcoll_sqlite.tar.xz link in the README file gives "Access Denied" page.

**Comment by Richard-Wai** [comment]
Sorry for seeing this issue so late after you submitted it. The issue has been fixed. Also note that the GCC 10.3.0 pack for FreeBSD 13.0 is coming in the next day or so.

**Comment by ALPHA-60** [comment]
No problem, thanks a lot for resolving this.
