### ISSUE TITLE
FreeBSD 13 gnat-10.3.0-gpr.tar.xz and gnat-10.3.0-gnatcoll_sqlite.tar.xz link to a 403 page.

### ISSUE THREAD

**Issue by ALPHA-60** [annexi-strayline/gnat-packs#2]
This issue is similar to #1.

**Comment by Richard-Wai** [comment]
In fact, I have not built these packages yet - they will follow soon!

**Comment by Richard-Wai** [comment]
Ooops I've made an error - I was thinking of the latest Linux build. The FreeBSD packages are built, but there seems to be some incorrect access settings on AWS. I'll look into this.

**Comment by Richard-Wai** [comment]
Resolved! Thanks for pointing this out.
